apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-server-crt
  namespace: cert-manager
spec:
  secretName: home-server-crt-secret
  dnsNames:
  - cobbles.io
  - '*.cobbles.io'
  issuerRef:
    name: home-server-letsencrypt
    kind: Issuer
    group: cert-manager.io
