apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: home-server-letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: home-server-tls
    solvers:
    - dns01:
        route53:
          region: ap-southeast-2
          accessKeyID: AKIAXUI2WHVNBVA62VXR
          secretAccessKeySecretRef:
            key: AWS_SECRET_ACCESS_KEY
            name: home-server-aws-cli-secret
