apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: app
deploy:
  kustomize:
    paths: ["k8s/overlays/dev"]

profiles:
- name: prod
  deploy:
    kustomize:
      paths: ["k8s/overlays/prod"]
