apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-server-persistent-volume
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt"
