apiVersion: v1
kind: Service
metadata:
  name: plex
  labels:
    app: plex
spec:
  type: NodePort
  selector:
    app: plex
    tier: backend
  ports:
  - protocol: TCP
    port: 32400
    nodePort: 32400
