apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    app: sonarr
spec:
  selector:
    matchLabels:
      app: sonarr
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: sonarr
        tier: backend
        track: stable
    spec:
      containers:
      - name: sonarr
        image: linuxserver/sonarr:version-3.0.6.1265
        volumeMounts:
        - name: sonarr-persistent-storage
          mountPath: /config
          subPath: sonarr/config
        - name: sonarr-persistent-storage
          mountPath: /tv
          subPath: tv/
        - name: sonarr-persistent-storage
          mountPath: /downloads
          subPath: downloads/
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Australia/Syndey"
      volumes:
      - name: sonarr-persistent-storage
        persistentVolumeClaim:
          claimName: home-server-pvc