apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  labels:
    app: jackett
spec:
  selector:
    matchLabels:
      app: jackett
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: jackett
        tier: backend
        track: stable
    spec:
      containers:
      - name: jackett
        image: linuxserver/jackett:version-v0.18.827
        volumeMounts:
        - name: jackett-persistent-storage
          mountPath: /config
          subPath: jackett/config
        - name: jackett-persistent-storage
          mountPath: /downloads
          subPath: downloads/
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Australia/Syndey"
      volumes:
      - name: jackett-persistent-storage
        persistentVolumeClaim:
          claimName: home-server-pvc
