name: CI

on: [push]

env:
  REGISTRY: docker.pkg.github.com
  PACKAGE_REPOSITROY: docker.pkg.github.com/${{ github.repository }}
  CI_TAG: ${{ github.sha }}
  SKAFFOLD_VERSION: 1.14.0
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v1
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}        
      - name: Skaffold build
        uses: hiberbee/github-action-skaffold@latest
        with:
          skaffold-version: ${{ env.SKAFFOLD_VERSION }}
          command: build
          profile: ci # refer to skaffold.yaml

  lint:
    name: Lint
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: TS Lint
        run: docker run ${{ env.PACKAGE_REPOSITROY }}/media-server:${{ env.CI_TAG }} npm run-script lint

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Jest test
        run: docker run ${{ env.PACKAGE_REPOSITROY }}/media-server:${{ env.CI_TAG }} npm run-script test-once
  
  publish:
    name: Publish to Github packages
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v1
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}        
      - name: Skaffold build
        uses: hiberbee/github-action-skaffold@latest
        with:
          skaffold-version: ${{ env.SKAFFOLD_VERSION }}
          command: build

  # deploy:
  #   name: Deploy to AWS EKS
  #   if: ${{ startsWith(github.ref, 'refs/tags/') }}
  #   needs: publish
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to AWS
  #       run: echo "deploying to aws" 
