name: CI

on: [push]

env:
  REGISTRY: docker.pkg.github.com
  SKAFFOLD_VERSION: 1.15.0

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v1
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Skaffold build
        uses: hiberbee/github-action-skaffold@latest
        with:
          skaffold-version: ${{ env.SKAFFOLD_VERSION }}
          command: build
